version: '2'
services:
  droppy:
    container_name: droppy
    image: alex21311/droppy
    ports:
      - 8989:8989
    volumes:
      - ./config:/config
      - ./data:/files
    restart: unless-stopped
